//
//  GSSALinkDePagoCorreoRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 12/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class GSSALinkDePagoCorreoRouter: GSSALinkDePagoCorreoWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    public static func createModule(delegate: GSSALinkDePagoCorreoViewControllerDelegate) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSALinkDePagoCorreoViewController(nibName: nil, bundle:  Bundle(for: GSSALinkDePagoCorreoRouter.self))
        let router = GSSALinkDePagoCorreoRouter()
        let presenter = GSSALinkDePagoCorreoPresenter(interface: view, router: router)
        
        view.presenter = presenter
        view.delegate = delegate
        router.viewController = view
        
        return view
    }
    
    public static func createModuleWithNavigation() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSALinkDePagoCorreoViewController(nibName: nil, bundle:  Bundle(for: GSSALinkDePagoCorreoRouter.self))
        let router = GSSALinkDePagoCorreoRouter()
        let presenter = GSSALinkDePagoCorreoPresenter(interface: view, router: router)
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
}
