//
//  GSSALinkDePagoCorreoPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 12/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSALinkDePagoCorreoPresenter: GSSALinkDePagoCorreoPresenterProtocol {
    weak private var view: GSSALinkDePagoCorreoViewProtocol?
    private let router: GSSALinkDePagoCorreoWireframeProtocol

    init(interface: GSSALinkDePagoCorreoViewProtocol, router: GSSALinkDePagoCorreoWireframeProtocol) {
        self.view = interface
        self.router = router
    }
}
