//
//  BASACardStatementsProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASACardStatementsWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol BASACardStatementsPresenterProtocol: AnyObject {
    func requestStatements(body: DebitCardStatementBody, StatementsResultData: @escaping (DebitCardStatementData?) -> ())
    func requestDocument(body: RequestDocumentBody, Document: @escaping (RequestDocumentResponse?) -> ())
}

//MARK: Interactor -
protocol BASACardStatementsInteractorProtocol: AnyObject {
  var presenter: BASACardStatementsPresenterProtocol?  { get set }
    func getStatements(body: DebitCardStatementBody, StatementsResultData: @escaping (DebitCardStatementData?) -> ())
    func getDocument(body: RequestDocumentBody, Document: @escaping (RequestDocumentResponse?) -> ())
}

//MARK: View -
protocol BASACardStatementsViewProtocol: AnyObject {

  var presenter: BASACardStatementsPresenterProtocol?  { get set }
}
