//
//  BASACardStatementsProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASACardStatementsWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASACardStatementsPresenterProtocol: class {

}

//MARK: Interactor -
protocol BASACardStatementsInteractorProtocol: class {

  var presenter: BASACardStatementsPresenterProtocol?  { get set }
}

//MARK: View -
protocol BASACardStatementsViewProtocol: class {

  var presenter: BASACardStatementsPresenterProtocol?  { get set }
}
