//
//  GSSAFundSetCVVPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSetCVVPresenter: GSSAFundSetCVVPresenterProtocol {

    weak private var view: GSSAFundSetCVVViewProtocol?
    var interactor: GSSAFundSetCVVInteractorProtocol?
    private let router: GSSAFundSetCVVWireframeProtocol

    init(interface: GSSAFundSetCVVViewProtocol, interactor: GSSAFundSetCVVInteractorProtocol?, router: GSSAFundSetCVVWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
