//
//  GSSAFundSetCVVRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSetCVVRouter: GSSAFundSetCVVWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSAFundSetCVVViewController(nibName: nil, bundle: Bundle.init(for: GSSAFundSetCVVRouter.self))
        let interactor = GSSAFundSetCVVInteractor()
        let router = GSSAFundSetCVVRouter()
        let presenter = GSSAFundSetCVVPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
