//
//  GSSAFundSetCVVViewController.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualTemplates
import GSSAVisualComponents

class GSSAFundSetCVVViewController: GSSAMasterViewController, GSSAFundSetCVVViewProtocol, UITextFieldDelegate {
    
    @IBOutlet weak var txtCVV: GSVCTextField!
    @IBOutlet weak var cardInfoView: GSSACardInfoView!
    
    var presenter: GSSAFundSetCVVPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.setNavigationBarHidden(false, animated: true)
        self.title = "Recarga tu tarjeta"
        txtCVV.delegate = self
        cardInfoView.setupInfo(name: "Elena Padilla López", bankName: "BBVA", accountNumber: "5678 8901 2345 6789")
    }
    
    override func viewDidAppear(_ animated: Bool) {
        setProgressLine(value: 0.25, animated: true)
    }

    @IBAction func next(_ sender: Any){
        let view = GSSACardFundResumeRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
}
