//
//  GSSAFundSetCVVInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSetCVVInteractor: GSSAFundSetCVVInteractorProtocol {

    weak var presenter: GSSAFundSetCVVPresenterProtocol?
}
