//
//  GSSAFundSetCVVRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSetCVVRouter: GSSAFundSetCVVWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(token: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSAFundSetCVVViewController(nibName: "GSSAFundSetCVVViewController", bundle: Bundle.init(for: GSSAFundAddCardRouter.self))
        let interactor = GSSAFundSetCVVInteractor()
        let router = GSSAFundSetCVVRouter()
        let presenter = GSSAFundSetCVVPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.token = token
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToNextFlow() {
        let view = GSSACardFundResumeRouter.createModule()
        viewController?.navigationController?.pushViewController(view, animated: true)
    }
    
    func goToError(message: String, isDouble: Bool) {
        guard let errorVC = viewController?.getErrorMPViewController(message: message, isDouble: isDouble) else { return }
        viewController?.navigationController?.pushViewController(errorVC, animated: true)
    }
}
