//
//  BASAMainHubCardsRouter.swift
//  GSSAFront
//
//  Created Andoni Suarez on 15/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

public class BASAMainHubCardsRouter: BASAMainHubCardsWireframeProtocol {
    weak var viewController: UIViewController?
    
    public static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = BASAMainHubCardsViewController(nibName: "BASAMainHubCardsViewController", bundle: Bundle(for: BASAMainHubCardsRouter.self))
        view.modalPresentationStyle = .fullScreen
        let interactor = BASAMainHubCardsInteractor()
        let router = BASAMainHubCardsRouter()
        let presenter = BASAMainHubCardsPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    public static func createModuleWithParams(accountNumber: [String:String]) -> UIViewController{
        // Change to get view from storyboard if not using progammatic UI
        let view = BASAMainHubCardsViewController(nibName: "BASAMainHubCardsViewController", bundle: Bundle(for: BASAMainHubCardsRouter.self))
        view.modalPresentationStyle = .fullScreen
        let interactor = BASAMainHubCardsInteractor()
        let router = BASAMainHubCardsRouter()
        let presenter = BASAMainHubCardsPresenter(interface: view, interactor: interactor, router: router)
        
        view.accountNumber = accountNumber
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
