//
//  BASAMainHubCardsProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 17/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASAMainHubCardsWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASAMainHubCardsPresenterProtocol: class {
    func requestBalance(Account:[String:String], Balance: @escaping (BalanceResponse?) -> ())
    func requestDebitCardMovements(Body: MovimientosBody, Movements: @escaping (DebitCardTransaction?) -> ())
}

//MARK: Interactor -
protocol BASAMainHubCardsInteractorProtocol: class {
  var presenter: BASAMainHubCardsPresenterProtocol?  { get set }
    func TryGetDebitCardBalance(Account:[String:String], Balance: @escaping (BalanceResponse?) -> ())
    func TryGetDebitCardMovements(Body: MovimientosBody, Movements: @escaping (DebitCardTransaction?) -> ())
}

//MARK: View -
protocol BASAMainHubCardsViewProtocol: class {
  var presenter: BASAMainHubCardsPresenterProtocol?  { get set }
}
