//
//  BASAMainHubCardsInteractor.swift
//  GSSAFront
//
//  Created Desarrollo on 17/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSASessionInfo
import GSSAFunctionalUtilities

open class BASAMainHubCardsInteractor: GSSAURLSessionTaskCoordinatorBridge, BASAMainHubCardsInteractorProtocol{
    
    weak var presenter: BASAMainHubCardsPresenterProtocol?
    
    func tryGetUserActivations(UserActivationsResponse: @escaping () -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/prestamos/tarjeta-credito/v1/tarjetas/activaciones/busquedas"
        
        struct userLendsBody: Codable {}
        let body = userLendsBody.init()
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: body, environment: GLOBAL_ENVIROMENT) { (objRes: BalanceResponse?, error) in
            
            if error.code == 0 {
                
             //   UserActivationsResponse(objRes)
            } else {
                //UserActivationsResponse(nil)
                debugPrint(error)
            }
        }
        
    }
    
    func TryGetDebitCardBalance(Account:[String:String], Balance: @escaping (BalanceResponse?) -> ()){
        
        let requestBody = TransationBalanceRequest(transaccion: TransationItem(folio: (GSSISessionInfo.sharedInstance.gsUser.SICU?.encryptAlnova() ?? "")))
        
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/dinero/captacion/cuentas/v1/busquedas"
        
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: requestBody, environment: GLOBAL_ENVIROMENT) { (objRes: BalanceResponse?, error) in
//            self.tryGetUserActivations {
//                print("OK")
//            }
            if error.code == 0 {
                if (objRes?.resultado.cliente?.cuentas?.first?.saldoDisponible) != nil{
                    Balance(objRes)
                }else{
                    Balance(objRes)
                }
            } else {
                Balance(nil)
                debugPrint(error)
            }
        }
    }
    
    func TryGetDebitCardMovements(Body: MovimientosBody, Movements: @escaping (DebitCardTransaction?) -> ()){
        
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/dinero/captacion/cuentas/v1/movimientos/busquedas"
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: Body, environment: GLOBAL_ENVIROMENT) { (objRes: DebitCardTransaction?, error) in
            
            if error.code == 0 {
                Movements(objRes)
            } else {
                Movements(nil)
                debugPrint(error)
            }
        }
        
        
    }
    
    func tryGetUserLends(Lends: @escaping (LendsResponse?) -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/pagos/creditos/agenda-pagos/v1/credimax/pagos-pendientes"
        
        struct userLendsBody: Codable {}
        let body = userLendsBody.init()
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: body, environment: GLOBAL_ENVIROMENT) { (objRes: LendsResponse?, error) in
            debugPrint(objRes as Any)
            
            if error.code == 0 {
                Lends(objRes)
            } else {
                Lends(nil)
                debugPrint(error)
            }
        }
    }
    
    func tryGetCreditCardData(Body: CreditCardBody, CreditCardData: @escaping (CreditCardResponse?) -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/prestamos/tarjeta-credito/v1/tarjetas/busquedas"
        
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: Body, environment: GLOBAL_ENVIROMENT) { (objRes: CreditCardResponse?, error) in
            
            print(Body)
            
            debugPrint(objRes as Any)
            
            if error.code == 0 {
                CreditCardData(objRes)
            } else {
                CreditCardData(nil)
                debugPrint(error)
            }
        }
        
    }
    
    func tryGetCreditCardBalance(Body: CreditCardBalanceBody, CreditCardBalance: @escaping (CreditCardBalanceResponse?) -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/prestamos/tarjeta-credito/v1/tarjetas/saldos/busquedas"
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: Body, environment: GLOBAL_ENVIROMENT) { (objRes: CreditCardBalanceResponse?, error) in
            debugPrint(objRes as Any)
            
            if error.code == 0 {
                CreditCardBalance(objRes)
            } else {
                CreditCardBalance(nil)
                debugPrint(error)
            }
        }
        
        
    }
    
    func tryGetCreditCardMovements(Body: CreditCardMovementsBody, CreditCardMovements: @escaping (CreditCardMovementsResponse?) -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/prestamos/tarjeta-credito/v1/tarjetas/movimientos/busquedas"
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: Body, environment: GLOBAL_ENVIROMENT) { (objRes: CreditCardMovementsResponse?, error) in
            debugPrint(objRes ?? "")
            
            if error.code == 0 {
                CreditCardMovements(objRes)
            } else {
                CreditCardMovements(nil)
                debugPrint(error)
            }
        }
    }
}

