//
//  BASACardConfigProtocols.swift
//  TEST3
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASACardConfigWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol BASACardConfigPresenterProtocol: AnyObject {
    func requestCardStatus(CardSearchResponse: @escaping (CardStatusResponse?) -> ())
    func requestCardInfo(DebitCardInfoResponse: @escaping (DebitCardInfoResponse?) -> ())
}

//MARK: Interactor -
protocol BASACardConfigInteractorProtocol: AnyObject {
  var presenter: BASACardConfigPresenterProtocol?  { get set }
    func tryGetRequestedCardStatus(CardSearchResponse: @escaping (CardStatusResponse?) -> ())
    func tryGetRequestCardInfo(DebitCardInfoResponse: @escaping (DebitCardInfoResponse?) -> ())
}

//MARK: View -
protocol BASACardConfigViewProtocol: AnyObject {

  var presenter: BASACardConfigPresenterProtocol?  { get set }
}
