//
//  BASACardConfigRouter.swift
//  TEST3
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BASACardConfigRouter: BASACardConfigWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(credit: Bool) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = BASACardConfigViewController(nibName: nil, bundle: Bundle(for: BASACardConfigRouter.self))
        let interactor = BASACardConfigInteractor()
        let router = BASACardConfigRouter()
        let presenter = BASACardConfigPresenter(interface: view, interactor: interactor, router: router)
        
        view.credit = credit
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
