//
//  BASACardConfigInteractor.swift
//  TEST3
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSASessionInfo
import GSSAFunctionalUtilities

class BASACardConfigInteractor:  GSSAURLSessionTaskCoordinatorBridge,  BASACardConfigInteractorProtocol {
    weak var presenter: BASACardConfigPresenterProtocol?
    
    func tryGetRequestedCardStatus(CardSearchResponse: @escaping () -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/dinero/captacion/gestion-tarjetas-fisicas/v1/tarjetas/solicitudes/busquedas/estatus"
  
        let bodyTest = CardConfigCardSearchBody.init(transaccion: CardConfigCardSearchTransaccion.init(primerTokenVerificacion: "fac2ac44565db5312fb407c3c9482d04", sicu: GSSISessionInfo.sharedInstance.gsUser.SICU, numeroCuenta: GSSISessionInfo.sharedInstance.gsUser.mainAccount, idTipoTarjeta: "CP"))
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, objBody: bodyTest, environment: GLOBAL_ENVIROMENT) { (objRes: DebitCardStatementData?, error) in
            debugPrint(objRes as Any)
            if error.code == 0 {
                print("correcto")
                debugPrint(objRes as Any)
            } else {
                debugPrint(error)
            }
        }
    }
    
    
}
