//
//  BASACardConfigProtocols.swift
//  TEST3
//
//  Created Desarrollo on 13/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASACardConfigWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASACardConfigPresenterProtocol: class {
    func requestCardStatus(CardSearchResponse: @escaping () -> ())
}

//MARK: Interactor -
protocol BASACardConfigInteractorProtocol: class {
  var presenter: BASACardConfigPresenterProtocol?  { get set }
    func tryGetRequestedCardStatus(CardSearchResponse: @escaping () -> ())
}

//MARK: View -
protocol BASACardConfigViewProtocol: class {

  var presenter: BASACardConfigPresenterProtocol?  { get set }
}
