//
//  GSSACardConfigEntity.swift
//  GSSAMyMoney
//
//  Created by Desarrollo on 10/08/21.
//

import Foundation


public struct customToken{
    static var shared = customToken()
    var bearer = "eyJraWQiOiJkczdRNlBTbE9ZNStuMnJjXC9PdjJqTGp5eWZRS2VJdmFjRXcwWHlNQm80cz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxOGg4dmFudnJoNHB1aTFscm50YzFuaWxqZiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiVXN1YXJpb1wvZGVsZXRlIFVzdWFyaW9cL3JlYWQgVXN1YXJpb1wvdXBkYXRlIiwiYXV0aF90aW1lIjoxNjI5MTYzMzQ5LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9FaEZuSU9JRzAiLCJleHAiOjE2MjkxNjY5NDksImlhdCI6MTYyOTE2MzM0OSwidmVyc2lvbiI6MiwianRpIjoiNDYwNzYwMjItNjlhMy00NDViLWE3NDUtMDdiNTgyOGI1MmQxIiwiY2xpZW50X2lkIjoiMThoOHZhbnZyaDRwdWkxbHJudGMxbmlsamYifQ.kg_0wqkMAkpjFuSpeltecfLzI28Asu_bTmCXx64W9J5P02UyDNNVbBoecR2ITCyxEIOwu8pH4zkWa1qAmIkbySm0lpsiu2J_tlessP5tg6s3WU8kq9LHn3zdjkDgHkWwrag_kyyrWXDs64_noOOXwUC9koRtsAM_MkHEKk1u4UThm_UpZgqFoxuAIrGJEZT-TSeArv0Z0NvyUDYpsVijVo7jSu088Z_5V775Lm2Ktw3CivVA__R2etUC-Ea38yKm6f2j2mEynnhzkWdxO5KhP81zhocsyR5ExqBmafBH41Q8CmrRGZ11DFCjTB7ojPsmrne3F2NWho_t2huukDRftg"
    private init() { }
}


// MARK: - CardConfigCardSearchBody
struct CardConfigCardSearchBody: Codable {
    var transaccion: CardConfigCardSearchTransaccion?
}

// MARK: - Transaccion
struct CardConfigCardSearchTransaccion: Codable {
    var primerTokenVerificacion, sicu, numeroCuenta, idTipoTarjeta: String?
}
