//
//  GSSACardPaymentBtnCoreViewViewController.swift
//  GSSAMyMoney
//
//  Created cvillegasa on 07/09/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSACardPaymentBtnCoreViewViewController: UIViewController, GSSACardPaymentBtnCoreViewViewProtocol {

	var presenter: GSSACardPaymentBtnCoreViewPresenterProtocol?
    
   

	override func viewDidLoad() {
        super.viewDidLoad()
        self.presenter?.registerNotifications()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        self.present(GSSACardPaymentBtnSliderViewRouter.createModule(), animated: true, completion: nil)
    }
    
    func abortPayment() {
        self.dismiss(animated: true, completion: nil)
    }
    
    

}
