//
//  GSSACardPaymentBtnCoreViewProtocols.swift
//  GSSAMyMoney
//
//  Created cvillegasa on 07/09/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSACardPaymentBtnCoreViewWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSACardPaymentBtnCoreViewPresenterProtocol: class {
    func registerNotifications()
}

//MARK: Interactor -
protocol GSSACardPaymentBtnCoreViewInteractorProtocol: class {

  var presenter: GSSACardPaymentBtnCoreViewPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSACardPaymentBtnCoreViewViewProtocol: class {
    func abortPayment()
  var presenter: GSSACardPaymentBtnCoreViewPresenterProtocol?  { get set }
}
