//
//  GSSAActivateCreditCardProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 31/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSAActivateCreditCardWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSAActivateCreditCardPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSAActivateCreditCardInteractorProtocol: class {

  var presenter: GSSAActivateCreditCardPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSAActivateCreditCardViewProtocol: class {

  var presenter: GSSAActivateCreditCardPresenterProtocol?  { get set }
}
