//
//  GSSAActivateCreditCardRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 31/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAActivateCreditCardRouter: GSSAActivateCreditCardWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSAActivateCreditCardViewController(nibName: nil, bundle: Bundle.init(for: GSSAActivateCreditCardRouter.self))
        let interactor = GSSAActivateCreditCardInteractor()
        let router = GSSAActivateCreditCardRouter()
        let presenter = GSSAActivateCreditCardPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
