//
//  GSSAActivateCreditCardPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 31/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAActivateCreditCardPresenter: GSSAActivateCreditCardPresenterProtocol {

    weak private var view: GSSAActivateCreditCardViewProtocol?
    var interactor: GSSAActivateCreditCardInteractorProtocol?
    private let router: GSSAActivateCreditCardWireframeProtocol

    init(interface: GSSAActivateCreditCardViewProtocol, interactor: GSSAActivateCreditCardInteractorProtocol?, router: GSSAActivateCreditCardWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
