//
//  GSSACardPaymentBtnSliderViewPresenter.swift
//  GSSAMyMoney
//
//  Created cvillegasa on 07/09/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSACardPaymentBtnSliderViewPresenter: GSSACardPaymentBtnSliderViewPresenterProtocol {

    weak private var view: GSSACardPaymentBtnSliderViewViewProtocol?
    var interactor: GSSACardPaymentBtnSliderViewInteractorProtocol?
    private let router: GSSACardPaymentBtnSliderViewWireframeProtocol

    init(interface: GSSACardPaymentBtnSliderViewViewProtocol, interactor: GSSACardPaymentBtnSliderViewInteractorProtocol?, router: GSSACardPaymentBtnSliderViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    
    

    func closeParent() {
        NotificationCenter.default.post(name: Notification.Name.init("abortPaymentNotification"), object: nil)
    }

    
    

}
