//
//  GSSAPhysicalCardRequestAddressProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSAPhysicalCardRequestAddressWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol GSSAPhysicalCardRequestAddressPresenterProtocol: AnyObject {
    func requestLocationInfo(CP: String, LocationInfo: @escaping (zipResponse?) -> ())
}

//MARK: Interactor -
protocol GSSAPhysicalCardRequestAddressInteractorProtocol: AnyObject {
    var presenter: GSSAPhysicalCardRequestAddressPresenterProtocol?  { get set }
    func tryGetLocationInfo(CP: String, LocationInfo: @escaping (zipResponse?) -> ())
}

//MARK: View -
protocol GSSAPhysicalCardRequestAddressViewProtocol: AnyObject {

  var presenter: GSSAPhysicalCardRequestAddressPresenterProtocol?  { get set }
}
