//
//  GSSACardScannerPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSACardScannerPresenter: GSSACardScannerPresenterProtocol {

    weak private var view: GSSACardScannerViewProtocol?
    var interactor: GSSACardScannerInteractorProtocol?
    private let router: GSSACardScannerWireframeProtocol

    init(interface: GSSACardScannerViewProtocol, interactor: GSSACardScannerInteractorProtocol?, router: GSSACardScannerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
