//
//  GSSACardScannerProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSACardScannerWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSACardScannerPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSACardScannerInteractorProtocol: class {

  var presenter: GSSACardScannerPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSACardScannerViewProtocol: class {

  var presenter: GSSACardScannerPresenterProtocol?  { get set }
}
