//
//  GSSACardFundResumePresenter.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSACardFundResumePresenter: GSSACardFundResumePresenterProtocol {

    weak private var view: GSSACardFundResumeViewProtocol?
    var interactor: GSSACardFundResumeInteractorProtocol?
    private let router: GSSACardFundResumeWireframeProtocol

    init(interface: GSSACardFundResumeViewProtocol, interactor: GSSACardFundResumeInteractorProtocol?, router: GSSACardFundResumeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
