//
//  GSSACardFundResumeProtocols.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSACardFundResumeWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSACardFundResumePresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSACardFundResumeInteractorProtocol: class {

  var presenter: GSSACardFundResumePresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSACardFundResumeViewProtocol: class {

  var presenter: GSSACardFundResumePresenterProtocol?  { get set }
}
