//
//  GSSACardFundResumeViewController.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualComponents
import GSSAVisualTemplates
import GSSAInterceptor

class GSSACardFundResumeViewController: GSVTGenericResumeViewController, GSSACardFundResumeViewProtocol, GSVTDigitalSignDelegate {

	var presenter: GSSACardFundResumePresenterProtocol?
    var digitalSign : GSVTDigitalSignViewController?
    var ticket : GSVTTicketOperationController?
    
    //MARK: - Life Cycle Methods
	override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Recarga tu tarjeta"
        configureCells()
        configureComponents()
    }

    override func viewWillAppear(_ animated: Bool) {
        
    }
    
    func forgotDigitalSign(_ forgotSecurityCodeViewController: UIViewController?) {
        print("forgot")
    }
    
    func verification(_ success: Bool, withSecurityCode securityCode: String?, andUsingBiometric usingBiometric: Bool) {
        let view = GSSAFundWebViewRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
    
    func configureCells(){
    var cells:[GSVTResumeCellInfo] = []
    
    let origin = GSVTResumeCellInfo(sectionTitle: "Desde qué tarjeta recibes",
                                mainInfo: "BBVA****1234",
                                iconImage: UIImage(named: "paypalCardSAIcon")) {
        
        self.popToViewController(ofClass: GSSAFundSelectCardRouter.self, animated: false)
    }
    cells.append(origin)
    
    let amount = GSVTResumeCellInfo(sectionTitle: "Cuánto quieres enviar",
                                        mainInfo: "$600.00",
                                        iconImage: UIImage(named: "profileSAIcon")) {
        self.popToViewController(ofClass: GSSAFundAddCardRouter.self, animated: false)
    }
    cells.append(amount)
    
    let extraData = GSVTResumeCellInfo(sectionTitle: "Datos de tu envío",
                                        subTitle: "Comisión",
                                    mainInfo: "$5.00",
                                    iconImage: UIImage(named: "legalInfoSAIcon"))
    
    cells.append(extraData)
    

    tableView.data = cells
}
}
//MARK: - GSVCSliderButtonDelegate
extension GSSACardFundResumeViewController: GSVCSliderButtonDelegate {
    func slideDidFinish(_ sender: GSVCSliderButton) {
        sender.resetSliderState(animated: true)
        let verification = GSVTDigitalSignViewController(delegate: self)
        verification.modalPresentationStyle = .fullScreen
        verification.bShouldWaitForNewToken = false
        present(verification, animated: true, completion: nil)
    }
}

//MARK: - Private functions
extension GSSACardFundResumeViewController {
    private func configureComponents(){
        btnContinue = GSVCSliderButton(
            delegate: self,
            strInstruction: "Desliza para enviar",
            withSuccesText: true,
            thumbnailImage: UIImage(named: "arrastrar3"),
            frame: CGRect(x: 0,y: 0, width: self.view.frame.width, height: 64)
        )
    }
    
    private func popToViewController(ofClass: AnyClass, animated: Bool = true){
        if  let nav = self.navigationController,
            let vc = nav.viewControllers.last(where: { $0.isKind(of: ofClass) }) {
            nav.popToViewController(vc, animated: animated)
      }
    }
    
}
