//
//  GSSAFundSelectCardViewController.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualComponents

class GSSAFundSelectCardViewController: GSSAMasterViewController, GSSAFundSelectCardViewProtocol {

    @IBOutlet weak var lblSubtitle: GSVCLabel!
    
	var presenter: GSSAFundSelectCardPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Recarga tu tarjeta"
    }

    override func viewDidAppear(_ animated: Bool) {
        setProgressLine(value: 0.25, animated: true)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(false, animated: false)
    }
    
    @IBAction func addCard(_ sender: Any){
        let view = GSSAFundSetCardNumberRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
}
