//
//  GSSAFundSelectCardProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSAFundSelectCardWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSAFundSelectCardPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSAFundSelectCardInteractorProtocol: class {

  var presenter: GSSAFundSelectCardPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSAFundSelectCardViewProtocol: class {

  var presenter: GSSAFundSelectCardPresenterProtocol?  { get set }
}
