//
//  GSSAFundSelectCardInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import baz_ios_sdk_link_pago
import GSSASessionInfo


class GSSAFundSelectCardInteractor: GSSAFundSelectCardInteractorProtocol {

    weak var presenter: GSSAFundSelectCardPresenterProtocol?
    
    //let email: String? = Optional.some("tiwasos367@ppp998.com")
    
    //MARK: - Properties
    private let afiliationNumber: String? = GSSAFundSharedVariables.shared.numeroAfiliacion
    private let email = GSSISessionInfo.sharedInstance.gsUser.email?.lowercased()
    //private let email = mail
    
    func getCards() {
        guard let usrICU = GSSISessionInfo.sharedInstance.gsUser.SICU else { self.presenter?.getCardsError()
            return }
        guard let email = email,
              let afiliationNumber = afiliationNumber else {
            self.presenter?.getCardsError()
            return
        }
        
        LNKPG_Facade.shared.getListCard(xicu : usrICU, numeroAfiliacion: afiliationNumber, email: email, success: { [weak self] cards in
            guard let self = self else { return }
            
            guard let cards = cards else {
                self.presenter?.getCardsError()
                return
            }
            
            self.presenter?.getCardsSuccess(cards: cards)
            
        }, failure: { [weak self] message in
            guard let self = self else { return }
            
           
            self.presenter?.getCardsError()
        })
    }
    
    func deleteCard(body request: LNKPG_TokenCardDeleteRequestFacade) {
        LNKPG_Facade.shared.postDeleteCard(card: request, success:{ [weak self] response in
            guard let self = self else { return }
            
            guard let response = response else {
                self.presenter?.deleteCardError()
                return
            }
            
            self.presenter?.deleteCardSuccess(response: response)
            
        }, failure: { [weak self] error in
            guard let self = self else { return }
            self.presenter?.deleteCardError()
        })
    }
    
    func getEccomerceInformation() {
        //self.requestEcommerceSMMInformation()
        guard let afiliationNumber = afiliationNumber else {
            self.presenter?.getEccomerceInformationError()
            return
        }

        LNKPG_Facade.shared.Initialize(environment: .release)
        LNKPG_Facade.shared.getEcommerceInformation(numeroAfiliacion: afiliationNumber, success: { [weak self] response in
            guard let self = self else { return }

            guard let response = response else {
                self.presenter?.getEccomerceInformationError()
                return
            }

            GSSAFundSharedVariables.shared.ecommerceResponse = response
            
            self.requestEcommerceSMMInformation()
            
          //  self.presenter?.getEccomerceSMMInformationSuccess()
        }, failure: {  [weak self] message in
            guard let self = self else { return }

            
            self.presenter?.getEccomerceInformationError()
        })
    }
    
    
}

//MARK: - Private functions
extension GSSAFundSelectCardInteractor {
    private func requestEcommerceSMMInformation(){
        guard let email = email,
              let afiliationNumber = afiliationNumber else {
            self.presenter?.getEccomerceInformationError()
            return 
        }
        
        LNKPG_Facade.shared.getEcommerceSMMInformation(numeroAfiliacion: afiliationNumber, email: email) { [weak self] (information) in
            guard let self = self else { return }

            if let response = information {
                GSSAFundSharedVariables.shared.ecommerceSMMIResponse = response
            }
            guard let _ = information else {
                self.presenter?.getEccomerceInformationError()
                return
            }
            self.presenter?.getEccomerceSMMInformationSuccess()
        } failure: {
            [weak self] message in
            guard let self = self else { return }
            self.presenter?.getEccomerceInformationError()
        }
    }
}
