//
//  GSSAFundSelectCardRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSelectCardRouter: GSSAFundSelectCardWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSAFundSelectCardViewController(nibName: nil, bundle: Bundle.init(for: GSSAFundSelectCardRouter.self))
        let interactor = GSSAFundSelectCardInteractor()
        let router = GSSAFundSelectCardRouter()
        let presenter = GSSAFundSelectCardPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
