//
//  GSSAFundSelectCardPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSelectCardPresenter: GSSAFundSelectCardPresenterProtocol {

    weak private var view: GSSAFundSelectCardViewProtocol?
    var interactor: GSSAFundSelectCardInteractorProtocol?
    private let router: GSSAFundSelectCardWireframeProtocol

    init(interface: GSSAFundSelectCardViewProtocol, interactor: GSSAFundSelectCardInteractorProtocol?, router: GSSAFundSelectCardWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
