//
//  GSSAMovementPreviewInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 13/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAMovementPreviewInteractor: GSSAMovementPreviewInteractorProtocol {

    weak var presenter: GSSAMovementPreviewPresenterProtocol?
}
