//
//  GSSAMovementPreviewPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 13/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAMovementPreviewPresenter: GSSAMovementPreviewPresenterProtocol {

    weak private var view: GSSAMovementPreviewViewProtocol?
    var interactor: GSSAMovementPreviewInteractorProtocol?
    private let router: GSSAMovementPreviewWireframeProtocol

    init(interface: GSSAMovementPreviewViewProtocol, interactor: GSSAMovementPreviewInteractorProtocol?, router: GSSAMovementPreviewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func requestGetSPEIDetail(Body: SPEIDetailBody, claveRastreo: String,  Response: @escaping (SPEIDetailTransactionResponse?) -> ()){
        interactor?.tryGetSPEIDetail(Body: Body, claveRastreo: claveRastreo, Response: Response)
    }
}
