//
//  GSSAMovementPreviewInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 13/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSAFunctionalUtilities
import GSSASessionInfo

class GSSAMovementPreviewInteractor: GSSAURLSessionTaskCoordinatorBridge, GSSAMovementPreviewInteractorProtocol {
    weak var presenter: GSSAMovementPreviewPresenterProtocol?
    
    public func tryGetSPEIDetail(Body: SPEIDetailBody, claveRastreo: String,  Response: @escaping (SPEIDetailTransactionResponse?) -> ())
    {
     
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/pagos/captacion/transferencias/v1/spei/busquedas"
        let claveRastreo = HeadersCustom.init(value: claveRastreo, forHTTPHeaderField: "x-idClaveRastreo")
        
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [claveRastreo], objBody: Body, environment: GLOBAL_ENVIROMENT) { (objRes: SPEIDetailTransactionResponse?, error) in
            debugPrint(objRes ?? "nil")
            
            if error.code == 0 {
                Response(objRes)
            } else {
                Response(nil)
                debugPrint(error)
            }
        }
    }
}   
