//
//  GSSATransferFromOtherBankRouter.swift
//  GSSAMyMoney
//
//  Created Andoni Suarez  on 18/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSATransferFromOtherBankRouter: GSSATransferFromOtherBankWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSATransferFromOtherBankViewController(nibName: nil, bundle: Bundle.init(for: GSSATransferFromOtherBankRouter.self))
        let interactor = GSSATransferFromOtherBankInteractor()
        let router = GSSATransferFromOtherBankRouter()
        let presenter = GSSATransferFromOtherBankPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
