//
//  GSSATransferFromOtherBankInteractor.swift
//  GSSAMyMoney
//
//  Created Andoni Suarez  on 18/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSATransferFromOtherBankInteractor: GSSATransferFromOtherBankInteractorProtocol {

    weak var presenter: GSSATransferFromOtherBankPresenterProtocol?
}
