//
//  GSSATransferFromOtherBankProtocols.swift
//  GSSAMyMoney
//
//  Created Andoni Suarez  on 18/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSATransferFromOtherBankWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSATransferFromOtherBankPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSATransferFromOtherBankInteractorProtocol: class {

  var presenter: GSSATransferFromOtherBankPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSATransferFromOtherBankViewProtocol: class {

  var presenter: GSSATransferFromOtherBankPresenterProtocol?  { get set }
}
