//
//  GSSAAddFundsMenuPresenter.swift
//  GSSAMyMoney
//
//  Created Andoni Suarez  on 18/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAAddFundsMenuPresenter: GSSAAddFundsMenuPresenterProtocol {

    weak private var view: GSSAAddFundsMenuViewProtocol?
    var interactor: GSSAAddFundsMenuInteractorProtocol?
    private let router: GSSAAddFundsMenuWireframeProtocol

    init(interface: GSSAAddFundsMenuViewProtocol, interactor: GSSAAddFundsMenuInteractorProtocol?, router: GSSAAddFundsMenuWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
