//
//  GSSAAddFundsMenuProtocols.swift
//  GSSAMyMoney
//
//  Created Andoni Suarez  on 18/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSAAddFundsMenuWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSAAddFundsMenuPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSAAddFundsMenuInteractorProtocol: class {

  var presenter: GSSAAddFundsMenuPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSAAddFundsMenuViewProtocol: class {

  var presenter: GSSAAddFundsMenuPresenterProtocol?  { get set }
}
