//
//  GSSADocumentReaderPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 06/09/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSADocumentReaderPresenter: GSSADocumentReaderPresenterProtocol {

    weak private var view: GSSADocumentReaderViewProtocol?
    var interactor: GSSADocumentReaderInteractorProtocol?
    private let router: GSSADocumentReaderWireframeProtocol

    init(interface: GSSADocumentReaderViewProtocol, interactor: GSSADocumentReaderInteractorProtocol?, router: GSSADocumentReaderWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
