//
//  GSSADocumentReaderInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 06/09/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSASessionInfo
import GSSAFunctionalUtilities

class GSSADocumentReaderInteractor: GSSAURLSessionTaskCoordinatorBridge,  GSSADocumentReaderInteractorProtocol {

    weak var presenter: GSSADocumentReaderPresenterProtocol?
}
