//
//  BASABeneficiaryListProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASABeneficiaryListWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASABeneficiaryListPresenterProtocol: class {

}

//MARK: Interactor -
protocol BASABeneficiaryListInteractorProtocol: class {

  var presenter: BASABeneficiaryListPresenterProtocol?  { get set }
}

//MARK: View -
protocol BASABeneficiaryListViewProtocol: class {

  var presenter: BASABeneficiaryListPresenterProtocol?  { get set }
}
