//
//  GSSANewBeneficiaryAddressProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSANewBeneficiaryAddressWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSANewBeneficiaryAddressPresenterProtocol: class {
    func requestLocationInfo(CP: String, LocationInfo: @escaping (zipResponse?) -> ())
}

//MARK: Interactor -
protocol GSSANewBeneficiaryAddressInteractorProtocol: class {
    var presenter: GSSANewBeneficiaryAddressPresenterProtocol?  { get set }
    func tryGetLocationInfo(CP: String, LocationInfo: @escaping (zipResponse?) -> ())
}

//MARK: View -
protocol GSSANewBeneficiaryAddressViewProtocol: class {

  var presenter: GSSANewBeneficiaryAddressPresenterProtocol?  { get set }
}
