//
//  GSSANewBeneficiaryAddressPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSANewBeneficiaryAddressPresenter: GSSANewBeneficiaryAddressPresenterProtocol {

    weak private var view: GSSANewBeneficiaryAddressViewProtocol?
    var interactor: GSSANewBeneficiaryAddressInteractorProtocol?
    private let router: GSSANewBeneficiaryAddressWireframeProtocol

    init(interface: GSSANewBeneficiaryAddressViewProtocol, interactor: GSSANewBeneficiaryAddressInteractorProtocol?, router: GSSANewBeneficiaryAddressWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func requestLocationInfo(CP: String, LocationInfo: @escaping (zipResponse?) -> ()) {
        interactor?.tryGetLocationInfo(CP: CP, LocationInfo: LocationInfo)
    }
}
