//
//  GSSARequestDebitCardProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 28/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSARequestDebitCardWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSARequestDebitCardPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSARequestDebitCardInteractorProtocol: class {

  var presenter: GSSARequestDebitCardPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSARequestDebitCardViewProtocol: class {

  var presenter: GSSARequestDebitCardPresenterProtocol?  { get set }
}
