//
//  BASANewBeneficiaryProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASANewBeneficiaryWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASANewBeneficiaryPresenterProtocol: class {

}

//MARK: Interactor -
protocol BASANewBeneficiaryInteractorProtocol: class {

  var presenter: BASANewBeneficiaryPresenterProtocol?  { get set }
}

//MARK: View -
protocol BASANewBeneficiaryViewProtocol: class {

  var presenter: BASANewBeneficiaryPresenterProtocol?  { get set }
}
