//
//  BASANewBeneficiaryProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSAFunctionalUtilities
import GSSASessionInfo
//MARK: Wireframe -
protocol BASANewBeneficiaryWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASANewBeneficiaryPresenterProtocol: class {
    func requestSetNewBeneficiary(Body: NewBeneficiaryBody, method: EKTHTTPRequestMethod, DataCard: @escaping (DigitalCardResponse?) -> ())
}

//MARK: Interactor -
protocol BASANewBeneficiaryInteractorProtocol: class {
    var presenter: BASANewBeneficiaryPresenterProtocol?  { get set }
    func trySetNewBeneficiary(Body: NewBeneficiaryBody, method: EKTHTTPRequestMethod, DataCard: @escaping (DigitalCardResponse?) -> ())
}

//MARK: View -
protocol BASANewBeneficiaryViewProtocol: class {

  var presenter: BASANewBeneficiaryPresenterProtocol?  { get set }
}
