//
//  GSDigitalCardConfigRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 22/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

open class GSDigitalCardConfigRouter: GSDigitalCardConfigWireframeProtocol {
    
    weak var viewController: UIViewController?
    
   public static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSDigitalCardConfigViewController(nibName: nil, bundle: Bundle(for: GSDigitalCardConfigRouter.self))
        let interactor = GSDigitalCardConfigInteractor()
        let router = GSDigitalCardConfigRouter()
        let presenter = GSDigitalCardConfigPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
