//
//  GSDigitalCardConfigInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 22/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSDigitalCardConfigInteractor: GSDigitalCardConfigInteractorProtocol {

    weak var presenter: GSDigitalCardConfigPresenterProtocol?
}
