//
//  GSSAFundSetCardNumberInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAFundSetCardNumberInteractor: GSSAFundSetCardNumberInteractorProtocol {

    weak var presenter: GSSAFundSetCardNumberPresenterProtocol?
}
