//
//  GSSAFundSetCardNumberRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import  baz_ios_sdk_link_pago

class GSSAFundSetCardNumberRouter: GSSAFundSetCardNumberWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSAFundSetCardNumberViewController(nibName: nil, bundle: Bundle.init(for: GSSAFundSetCardNumberRouter.self))
        let interactor = GSSAFundSetCardNumberInteractor()
        let router = GSSAFundSetCardNumberRouter()
        let presenter = GSSAFundSetCardNumberPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToAddAddress(_ view: UIViewController) {
        viewController?.navigationController?.pushViewController(view, animated: true)
    }
    
    func goBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
