//
//  GSSASetCVVPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSASetCVVPresenter: GSSASetCVVPresenterProtocol {

    weak private var view: GSSASetCVVViewProtocol?
    var interactor: GSSASetCVVInteractorProtocol?
    private let router: GSSASetCVVWireframeProtocol

    init(interface: GSSASetCVVViewProtocol, interactor: GSSASetCVVInteractorProtocol?, router: GSSASetCVVWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func requestSetCardCVV(body: SetCVVBody, CardSearchResponse: @escaping () -> ()){
        interactor?.trySetCardCVV(body: body, CardSearchResponse: CardSearchResponse)
    }
}
