//
//  GSSASetCVVViewController.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSASetCVVViewController: UIViewController, GSSASetCVVViewProtocol {

	var presenter: GSSASetCVVPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
