//
//  GSSACardNIPInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSAFunctionalUtilities
import GSSASessionInfo
import Foundation

class GSSACardNIPInteractor: GSSAURLSessionTaskCoordinatorBridge, GSSACardNIPInteractorProtocol {
    weak var presenter: GSSACardNIPPresenterProtocol?
    
    func tryRequestCardNIP(body: RequestNIPBody,  Response: @escaping () -> ()){
        self.urlPath = "https://apigateway.superappbaz.com/"
        self.strPathEndpoint = "integracion/superapp/dinero/captacion/gestion-tarjetas-fisicas/v1/tarjetas/busquedas/nip"
    
        sendRequest(strUrl: strPathEndpoint, method: .POST, arrHeaders: [], objBody: body, environment: .develop) { (objRes: PhysicalCardShippingAmountResponse?, error) in
            if error.code == 0 {
            } else {
                debugPrint(error)
            }
        }
    }
}
