//
//  GSSACardNIPProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSACardNIPWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol GSSACardNIPPresenterProtocol: AnyObject {
    func requestCardNIP(body: RequestNIPBody,  Response: @escaping () -> ())
}

//MARK: Interactor -
protocol GSSACardNIPInteractorProtocol: AnyObject {
    var presenter: GSSACardNIPPresenterProtocol?  { get set }
    func tryRequestCardNIP(body: RequestNIPBody,  Response: @escaping () -> ())
}

//MARK: View -
protocol GSSACardNIPViewProtocol: AnyObject {

  var presenter: GSSACardNIPPresenterProtocol?  { get set }
}
