//
//  GSSACardNIPProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GSSACardNIPWireframeProtocol: class {

}
//MARK: Presenter -
protocol GSSACardNIPPresenterProtocol: class {

}

//MARK: Interactor -
protocol GSSACardNIPInteractorProtocol: class {

  var presenter: GSSACardNIPPresenterProtocol?  { get set }
}

//MARK: View -
protocol GSSACardNIPViewProtocol: class {

  var presenter: GSSACardNIPPresenterProtocol?  { get set }
}
