//
//  GSSACardNIPInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 30/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSACardNIPInteractor: GSSACardNIPInteractorProtocol {

    weak var presenter: GSSACardNIPPresenterProtocol?
}
