//
//  GSSActivateDebitCardPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSActivateDebitCardPresenter: GSSActivateDebitCardPresenterProtocol {

    weak private var view: GSSActivateDebitCardViewProtocol?
    var interactor: GSSActivateDebitCardInteractorProtocol?
    private let router: GSSActivateDebitCardWireframeProtocol

    init(interface: GSSActivateDebitCardViewProtocol, interactor: GSSActivateDebitCardInteractorProtocol?, router: GSSActivateDebitCardWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
