//
//  GSSActivateDebitCardRouter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSActivateDebitCardRouter: GSSActivateDebitCardWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GSSActivateDebitCardViewController(nibName: nil, bundle: Bundle.init(for: GSSActivateDebitCardRouter.self))
        let interactor = GSSActivateDebitCardInteractor()
        let router = GSSActivateDebitCardRouter()
        let presenter = GSSActivateDebitCardPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
