//
//  GSSActivateDebitCardViewController.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 29/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSActivateDebitCardViewController: GSSAMasterViewController, GSSActivateDebitCardViewProtocol {

	var presenter: GSSActivateDebitCardPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Activa tu tarjeta"
        self.navigationController?.setNavigationBarHidden(false, animated: true)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(false, animated: false)
        setProgressLine(value: 0.25, animated: true)
    }
    
    @IBAction func next(_ sender: Any){
        let view = GSSASetCVVRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
}

