//
//  GSSALinkDePagoInteractor.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 12/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSAFunctionalUtilities

class GSSALinkDePagoInteractor: GSSAURLSessionTaskCoordinatorBridge, GSSALinkDePagoInteractorProtocol {

    weak var presenter: GSSALinkDePagoPresenterProtocol?
    
    func tryMailUpdate(body: UpdateMailBody, Response: @escaping (DigitalCardResponse?) -> ())
    {
        self.urlPath = "https://api.baz.app"
        self.strPathEndpoint = "/superapp/enrolamiento/gestion-usuarios/v1/usuarios/correo"
        
        sendRequest(strUrl: strPathEndpoint, method: .PUT, objBody: body, environment: GLOBAL_ENVIROMENT) { (objRes: DigitalCardResponse?, error) in
            debugPrint(objRes ?? "NiL")
            
            if error.code == 0 {
                Response(objRes)
            } else {
                Response(nil)
                debugPrint(error)
            }
        }
    }
    
}
