//
//  GSSALinkDePagoPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 12/07/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSALinkDePagoPresenter: GSSALinkDePagoPresenterProtocol {
    weak private var view: GSSALinkDePagoViewProtocol?
    var interactor: GSSALinkDePagoInteractorProtocol?
    private let router: GSSALinkDePagoWireframeProtocol

    init(interface: GSSALinkDePagoViewProtocol, interactor: GSSALinkDePagoInteractorProtocol?, router: GSSALinkDePagoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func requestMailUpdate(body: UpdateMailBody, Response: @escaping (DigitalCardResponse?) -> ()) {
        interactor?.tryMailUpdate(body: body, Response: Response)
    }
    
}
