//
//  BASACardLimitsPresenter.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BASACardLimitsPresenter: BASACardLimitsPresenterProtocol {
    weak private var view: BASACardLimitsViewProtocol?
    var interactor: BASACardLimitsInteractorProtocol?
    private let router: BASACardLimitsWireframeProtocol

    init(interface: BASACardLimitsViewProtocol, interactor: BASACardLimitsInteractorProtocol?, router: BASACardLimitsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func requestCardLimitUpdate(ammount: String, indicador: String, DataCard: @escaping (CardLimitsResponse?) -> ()){
        interactor?.tryUpdateCardLimit(ammount: ammount, indicador: indicador, DataCard: DataCard)
    }
}
