//
//  BASACardLimitsInteractor.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BASACardLimitsInteractor: BASACardLimitsInteractorProtocol {

    weak var presenter: BASACardLimitsPresenterProtocol?
}
