//
//  BASACardLimitsInteractor.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAServiceCoordinator
import GSSASecurityManager
import GSSASessionInfo
import GSSAFunctionalUtilities

class BASACardLimitsInteractor: GSSAURLSessionTaskCoordinatorBridge, BASACardLimitsInteractorProtocol {

    weak var presenter: BASACardLimitsPresenterProtocol?
    
    public func tryUpdateCardLimit(ammount: String, indicador: String, DataCard: @escaping (CardLimitsResponse?) -> ())
    {
        let integerAmmount = String(Int(Double(ammount) ?? 0) * 100)
        
        let body = CardLimitsBody.init(transaccion: CardLimitsTransaccion.init(primerTokenVerificacion: GSSISessionInfo.sharedInstance.gsUserToken, numeroTarjeta: GSSISessionInfo.sharedInstance.gsUser.account?.card?.encryptAlnova(), monto: integerAmmount.encryptAlnova(), indicadorLimite: indicador))
        
        self.urlPath = "https://api.baz.app"
        self.strPathEndpoint = "/superapp/dinero/captacion/gestion-tarjetas/v1/tarjetas/montos/limites"
        
//        self.urlPath = "https://apigateway.superappbaz.com/"
//        self.strPathEndpoint =      "integracion/superapp/dinero/captacion/gestion-tarjetas/v1/tarjetas/montos/limites"
        
        sendRequest(strUrl: strPathEndpoint, method: .PUT, arrHeaders: [], objBody: body, environment: GLOBAL_ENVIROMENT) { (objRes: CardLimitsResponse?, error) in
            
            print(body)
            
            debugPrint(objRes as Any)
            
            if error.code == 0 {
                DataCard(objRes)
            } else {
                DataCard(nil)
                debugPrint(error)
            }
        }
    }
    
}
