//
//  BASACardLimitsProtocols.swift
//  GSSAFront
//
//  Created Desarrollo on 14/06/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BASACardLimitsWireframeProtocol: class {

}
//MARK: Presenter -
protocol BASACardLimitsPresenterProtocol: class {

}

//MARK: Interactor -
protocol BASACardLimitsInteractorProtocol: class {

  var presenter: BASACardLimitsPresenterProtocol?  { get set }
}

//MARK: View -
protocol BASACardLimitsViewProtocol: class {

  var presenter: BASACardLimitsPresenterProtocol?  { get set }
}
