//
//  GSSAConfirmCardSavePresenter.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAConfirmCardSavePresenter: GSSAConfirmCardSavePresenterProtocol {

    weak private var view: GSSAConfirmCardSaveViewProtocol?
    var interactor: GSSAConfirmCardSaveInteractorProtocol?
    private let router: GSSAConfirmCardSaveWireframeProtocol

    init(interface: GSSAConfirmCardSaveViewProtocol, interactor: GSSAConfirmCardSaveInteractorProtocol?, router: GSSAConfirmCardSaveWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
