//
//  GSSAConfirmCardSaveInteractor.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GSSAConfirmCardSaveInteractor: GSSAConfirmCardSaveInteractorProtocol {

    weak var presenter: GSSAConfirmCardSavePresenterProtocol?
}
