//
//  GSSAConfirmCardSaveViewController.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualComponents

class GSSAConfirmCardSaveViewController: UIViewController, GSSAConfirmCardSaveViewProtocol {

    @IBOutlet weak var cardInfoView: GSSACardInfoView!
    @IBOutlet weak var saveView: UIView!
    @IBOutlet weak var editBtn: GSVCButton!
    
    var presenter: GSSAConfirmCardSavePresenterProtocol?

    //MARK: Life Cycle Methods
    override func viewDidLoad() {
        super.viewDidLoad()
        setupFakeData()
        setupUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    @IBAction func next(_ sender: Any) {
        let view = GSSAFundSetCVVRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
    
    @IBAction func close(_ sender: Any) {
        self.navigationController?.popViewController(animated: true)
    }
}

//MARK: - Private functions
extension GSSAConfirmCardSaveViewController {
    private func setupUI(){
        editBtn.setTitleColor(.GSVCPrincipal100, for: .normal)
        saveView.backgroundColor = .GSVCBase200
    }
    
    private func setupFakeData(){
        cardInfoView.setupInfo(name: "Elena Padilla López", bankName: "BBVA", accountNumber: "5678 8901 2345 6789")
    }
}
