//
//  GSSAConfirmCardSaveInteractor.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import baz_ios_sdk_link_pago

class GSSAConfirmCardSaveInteractor: GSSAConfirmCardSaveInteractorProtocol {

    weak var presenter: GSSAConfirmCardSavePresenterProtocol?
    
    func requestSaveCard(tokenCardRequest: LNKPG_TokenCardRequestFacade) {
        print(tokenCardRequest)
        LNKPG_Facade.shared.postCreateToken(token: tokenCardRequest) {[weak self] response in
            guard let self = self else  { return }
            
            if let response = response {
                if let _ = response.paySubscriptionId {
                    self.presenter?.onSuccess(response)
                }else{
                    self.presenter?.onError()
                }
                
            } else {
                self.presenter?.onError()
            }
            
        } failure: { [weak self] error in
            guard let self = self else  { return }
            
            print(error)
            self.presenter?.onError()
        }

    }
}
