//
//  GSSAConfirmCardSavePresenter.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import baz_ios_sdk_link_pago

class GSSAConfirmCardSavePresenter: GSSAConfirmCardSavePresenterProtocol {
    func showErrorTokenNoActivo() {
        
    }
    

    weak private var view: GSSAConfirmCardSaveViewProtocol?
    var interactor: GSSAConfirmCardSaveInteractorProtocol?
    private let router: GSSAConfirmCardSaveWireframeProtocol

    init(interface: GSSAConfirmCardSaveViewProtocol, interactor: GSSAConfirmCardSaveInteractorProtocol?, router: GSSAConfirmCardSaveWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func requestSaveCard(tokenCardRequest: LNKPG_TokenCardRequestFacade) {
        interactor?.requestSaveCard(tokenCardRequest: tokenCardRequest)
    }
    
    func onSuccess(_ response: LNKPG_TokenCardResponseFacade) {
        view?.onSuccess(response)
    }
    
    func onError() {
        view?.onError()
    }
    
    func onErrorTokenNoActivo() {
        self.view?.showErrorTokenNoActivo()
    }
    func showErrorTokenNoActivo(message: String, isDouble: Bool, isWarning: Bool) {
        self.router.goToError(message: message, isDouble: isDouble, isWarning: isWarning)
    }
    
    func goToNextFlow() {
        router.goToNextFlow()
    }
    
    func goToError(message: String, isDouble: Bool, isWarning: Bool) {
        router.goToError(message: message, isDouble: isDouble, isWarning: isWarning)
    }
    
    func returnTo(vc: AnyClass, animated: Bool) {
        router.returnTo(vc: vc, animated: animated)
    }
}
