//
//  GSSAConfirmCardSaveInteractor.swift
//  GSSAMyMoney
//
//  Created Usuario Phinder 2021 on 02/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import baz_ios_sdk_link_pago
import GSSASessionInfo

class GSSAConfirmCardSaveInteractor: GSSAConfirmCardSaveInteractorProtocol {

    weak var presenter: GSSAConfirmCardSavePresenterProtocol?
    
    func requestSaveCard(tokenCardRequest: LNKPG_TokenCardRequestFacade) {
        LNKPG_Facade.shared.postCreateToken(token: tokenCardRequest) {[weak self] response in
            guard let self = self else  { return }
            if let response = response {
                if let createdCardToken = response.paySubscriptionId {
                    LNKPG_Facade.shared.getListCard(numeroAfiliacion: GSSAFundSharedVariables.shared.numeroAfiliacion ?? "", email: (GSSISessionInfo.sharedInstance.gsUser.email ?? "").lowercased()) { tokens in
                        if let nonNilTokens = tokens {
                            for token in nonNilTokens {
                                if createdCardToken == token.token ?? ""{
                                    if !(token.activo ?? false) {
                                        self.presenter?.onErrorTokenNoActivo()
                                        return
                                    }
                                }
                            }
                            self.presenter?.onSuccess(response)
                        }
                    } failure: { error in
                        self.presenter?.onError()
                        return
                    }
                }else{
                    self.presenter?.onError()
                }
            } else {
                self.presenter?.onError()
            }
            
        } failure: { [weak self] error in
            guard let self = self else  { return }
            
            self.presenter?.onError()
        }

    }
}
