//
//  BASADigitalCardViewController.swift
//  BASAMyPaymentsScreens
//
//  Created BranchbitG on 14/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualComponents
import GSSASessionInfo
import GSSAPermissionsManager

enum CardType{
    case debit
    case credit
}

class BASADigitalCardViewController: UIViewController, BASADigitalCardViewProtocol, GSVCBottomAlertHandler {
    var bottomAlert: GSVCBottomAlert?
    var presenter: BASADigitalCardPresenterProtocol?
    
    //MARK: - Outlets
    
    @IBOutlet weak var DigitalCard: BASAShadowRadiusView!
    @IBOutlet weak var TopHeaderView     : UIView!
    @IBOutlet weak var CardBackgroundView: UIView!
    @IBOutlet weak var CVVCodeLabel      : GSVCLabel!
    @IBOutlet weak var AvaibleMoneyLabel : GSVCLabel!
    @IBOutlet weak var CardNumberLabel   : GSVCLabel!
    @IBOutlet weak var ExpTitleLabel     : GSVCLabel!
    @IBOutlet weak var ExpDateLabel      : GSVCLabel!
    @IBOutlet weak var TimerView         : BASACircularProgressView!
    @IBOutlet weak var configButton      : UIButton!
    @IBOutlet weak var viewContainerOn   : UIView!
    @IBOutlet weak var cvvView           : UIView!
    @IBOutlet weak var lockIcon          : UIImageView!
    @IBOutlet weak var btnCopy           : UIButton!
    @IBOutlet weak var optionsView       : UIView!
    @IBOutlet weak var btnClose          : UIButton!
    @IBOutlet weak var titleTopSpace     : NSLayoutConstraint!
    @IBOutlet weak var titleBottomSpace  : NSLayoutConstraint!
    
    var userBalance: String! 
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.ConfigureBlurCardView()
        self.TimerView.delegate = self
        
        
        if UIDevice.current.screenType == .iPhones_5_5s_5c_SE{
            titleTopSpace.constant = 10.0
            titleBottomSpace.constant = 10.0
        }
        
        if #available(iOS 13.0, *){}else{
            btnCopy.setImage(UIImage.copyIcon(), for: .normal)
            btnClose.setImage(UIImage(named: "close", in: Bundle.init(for: GSSAMovementPreviewViewController.self), compatibleWith: nil), for: .normal)
        }
        
        configButton.backgroundColor = UIColor(hue: 100/360, saturation: 26/100, brightness: 62/100, alpha: 1.0)
        configButton.layer.masksToBounds = true
        configButton.layer.cornerRadius = configButton.frame.width/2
        
        CardBackgroundView.layer.cornerRadius = 10
        CardBackgroundView.layer.masksToBounds = true
        
        CardBackgroundView.layer.borderWidth = 0.2
        CardBackgroundView.layer.borderColor = UIColor.lightGray.cgColor
        
        
        cvvView.layer.cornerRadius = 10
        cvvView.layer.masksToBounds = true
        
        cvvView.layer.borderWidth = 0.2
        cvvView.layer.borderColor = UIColor.lightGray.cgColor
        
        trygetLocation()
        
        if userBalance != nil{
            self.AvaibleMoneyLabel.text = userBalance.alnovaDecrypt().moneyFormat()
        }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        requestCVV()
        tagDebitDigitalCardViewDidAppear()
    }
    
    func requestCVV(){
        GSVCLoader.show()
        presenter?.makeDigitalDataRequest(Body: Transaction(transaccion: AccoutRequest.init(numeroCuenta: GSSISessionInfo.sharedInstance.gsUser.mainAccount?.replacingOccurrences(of: " ", with: "").encryptAlnova(), sicu: GSSISessionInfo.sharedInstance.gsUser.SICU?.encryptAlnova(), latitud: (GSPMLocationManager.shared.lastLocation?.coordinate.latitude.description.encryptAlnova() ?? "0.0".encryptAlnova()), longitud: (GSPMLocationManager.shared.lastLocation?.coordinate.longitude.description.encryptAlnova() ?? "0.0".encryptAlnova()))), DataCard: { [self] DataCard in
            GSVCLoader.hide()
            
            if DataCard != nil{
                self.StartTimer()
                UserDefaults.standard.set(DataCard!.resultado!.tarjeta?.numero ?? "0", forKey: "DigitalCardNumber")
                
                if DataCard?.resultado?.tarjeta?.estatus == "BLOQUEADA"{
                    lockCard()
                }else{
                    unLockCard()
                }
                
                CVVCodeLabel.text = DataCard!.resultado!.tarjeta?.cvv?.alnovaDecrypt().showOnlyNumbers
                CardNumberLabel.text = (DataCard!.resultado!.tarjeta?.numero?.alnovaDecrypt() ?? "0").tnuoccaFormat
                ExpDateLabel.text = DataCard?.resultado?.tarjeta?.fechaExpiracion?.alnovaDecrypt().replacingOccurrences(of: "-", with: "/")
                
                optionsView.isHidden = false
            }else{
                self.presentBottomAlertFullData(status: .error, message: "No podemos obtener tu tarjeta digital en este momento, intenta más tarde", attributedString: nil, canBeClosed: true, animated: true, showOptionalButton: true, optionalButtonText:nil)
            }
        })
    }
    
    func optionalAction() {
        print("Ok")
    }
    
    func ConfigureBlurCardView(){
        CardBackgroundView.blurBackground(style: .light, fallbackColor: .white)
    }
    
    func StartTimer(){
        TimerView.start(beginingValue: 180)
    }
    
    func lockCard(){
        UserDefaults.standard.setValue(true, forKey: "DigitalCardStatus")
        viewContainerOn.isHidden = true
        cvvView.isHidden = true
        lockIcon.isHidden = false
    }
    
    func unLockCard(){
        UserDefaults.standard.setValue(false, forKey: "DigitalCardStatus")
        viewContainerOn.isHidden = false
        cvvView.isHidden = false
        lockIcon.isHidden = true
    }
    
    func SetGradient(){
        let view = UIView(frame: CGRect(x: 0, y: 0, width: TopHeaderView.bounds.width, height: TopHeaderView.bounds.height))
        let gradient = CAGradientLayer()
        gradient.frame = view.bounds
        gradient.colors = [UIColor.GSVCPrincipal100.cgColor, UIColor.GSVCPrincipal100.cgColor]
        TopHeaderView.layer.insertSublayer(gradient, at: 0)
    }
    
    func trygetLocation(){
        GSPMAdminAccess.request(for: .location) { access, error in
            if !access {
                UIAlertController.sendToSettings(cancelAction: {
                    self.navigationController?.popViewController(animated: true)
                })
            }
        }
    }
    
    @IBAction func copyCardNumber(_ sender: Any){
        if CardNumberLabel.text?.count ?? 0 > 0{
            tagCopyDebitDigitalCardNumber()
            UIPasteboard.general.string = CardNumberLabel.text
            self.presentBottomAlertFullData(status: .success, message: "Número de tarjeta copiado al portapapeles", attributedString: nil, canBeClosed: true, animated: true, showOptionalButton: true, optionalButtonText:nil)
        }
    }
    
    @IBAction func TryDismiss(_ sender: Any) {
        TimerView.end()
        self.navigationController?.popViewController(animated: true)
    }
    
    @IBAction func openConfig(_ sender: Any){
        tagDebitDigitalCardConfigClick()
        let view = GSDigitalCardConfigRouter.createModule()
        self.navigationController?.pushViewController(view, animated: true)
    }
}

//MARK: - Extensions

extension UIView {
    func roundCorners(_ corners:UIRectCorner, radius: CGFloat) {
        let path = UIBezierPath(roundedRect: self.bounds, byRoundingCorners: corners, cornerRadii: CGSize(width: radius, height: radius))
        let mask = CAShapeLayer()
        mask.path = path.cgPath
        self.layer.mask = mask
    }
}

extension UIView {
    @objc func blurBackground(style: UIBlurEffect.Style, fallbackColor: UIColor) {
        if !UIAccessibility.isReduceTransparencyEnabled {
            self.backgroundColor = .clear
            
            let blurEffect = UIBlurEffect(style: style)
            let blurEffectView = UIVisualEffectView(effect: blurEffect)
            //always fill the view
            blurEffectView.frame = self.self.bounds
            blurEffectView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
            
            self.insertSubview(blurEffectView, at: 0)
        } else {
            self.backgroundColor = fallbackColor
        }
    }
}

extension BASADigitalCardViewController: TimerHandleDelegate {
    func counterUpdateTimeValue(with sender: BASACircularProgressView, newValue: Int) {
        print("Time \(newValue)")
    }
    
    func didStartTimer(sender: BASACircularProgressView) {
        print("Inicio tiempo")
    }
    
    func didEndTimer(sender: BASACircularProgressView) {
        if self.isOnScreen{
            GSVCLoader.show()
            requestCVV()
        }
    }
}
