//
//  GSSAFundWebViewProtocols.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol GSSAFundWebViewWireframeProtocol: class {
    func goToError(message: String, isDouble: Bool)
    func goToTicket(folio: String)
}

//MARK: Presenter -
protocol GSSAFundWebViewPresenterProtocol: class {
    
    func checkFund()
    func onSucess(folio: String)
    func onError(content: String?)
    
    func goToError(message: String, isDouble: Bool)
    func goToTicket(folio: String)
}

//MARK: Interactor -
protocol GSSAFundWebViewInteractorProtocol: class {
    
    var presenter: GSSAFundWebViewPresenterProtocol?  { get set }
    
    func checkFund()
}

//MARK: View -
protocol GSSAFundWebViewViewProtocol: class {
    
    var presenter: GSSAFundWebViewPresenterProtocol?  { get set }
    
    func onSucess(folio: String)
    func onError(content: String?)
}
