//
//  GSSAFundWebViewPresenter.swift
//  GSSAMyMoney
//
//  Created Desarrollo on 03/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GSSAVisualComponents

class GSSAFundWebViewPresenter: GSSAFundWebViewPresenterProtocol {

    weak private var view: GSSAFundWebViewViewProtocol?
    var interactor: GSSAFundWebViewInteractorProtocol?
    private let router: GSSAFundWebViewWireframeProtocol

    init(interface: GSSAFundWebViewViewProtocol, interactor: GSSAFundWebViewInteractorProtocol?, router: GSSAFundWebViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func checkFund() {
        interactor?.checkFund()
    }
    
    func onSucess(folio: String) {
        GSVCLoader.hide()
        view?.onSucess(folio: folio)
    }
    
    func onError(content: String?) {
        GSVCLoader.hide()
        view?.onError(content: content)
    }

    func goToTicket(folio: String) {
        GSVCLoader.hide()
        router.goToTicket(folio: folio)
    }
    
    func goToError(message: String, isDouble: Bool) {
        GSVCLoader.hide()
        router.goToError(message: message, isDouble: isDouble)
    }
}
